name: "Build, tag, push Docker image"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get short SHA
        # Credits: https://github.community/u/kthy in thread https://github.community/t/add-short-sha-to-github-context/16418/10
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:latest
            ${{ secrets.DOCKERHUB_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ steps.slug.outputs.sha8 }}
